services:
  - type: web
    name: portefolio-projet-api
    env: docker
    plan: starter
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: APP_FRONTEND_URL
        value: https://portefolio-projet.onrender.com
      - key: DATABASE_URL
        sync: false

  - type: web
    name: portefolio-projet
    env: docker
    plan: starter
    dockerContext: frontend
    dockerfilePath: frontend/Dockerfile
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://portefolio-projet-api.onrender.com

  - type: pserv
    name: portfolio-postgres
    env: docker
    plan: starter
    image:
      url: postgres:16-alpine
